// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/trainmember/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainmember/[id]/index.get').default>>>>
    }
    '/api/trainmember/create/confirm': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainmember/create/confirm.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainmember/create/confirm.post').default>>>>
    }
    '/api/trainmember/create': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainmember/create/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainmember/create/index.post').default>>>>
    }
    '/api/trainmember/create/steps': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainmember/create/steps.get').default>>>>
    }
    '/api/trainmember/create/train': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainmember/create/train.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainmember/create/train.post').default>>>>
    }
    '/api/trainmember': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/trainmember/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_glezbnorfajjudi66ewcjck7gy/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}